    ('Accessoires', 0),
    ('Monitoren', 1),
    ('Muizen', 1),
    ('Speakers', 1),
    ('Toetsenborden', 1),
    ('Desktops', 0),
    ('All-in-ones', 6),
    ('Tower', 6),
    ('Componenten', 0),
    ('Moederborden', 9),
    ('Processoren', 9),
    ('SSD''s', 9),
    ('Videokaarten', 9),
    ('Laptops', 0),
    ('Muziek', NULL),
    ('Instrumenten', 15),
    ('Gitaren en versterkers', 16),
    ('Akoestische gitaren', 17),
    ('Versterkers', 18),
    ('Drumstellen', 16),
    ('Blaasinstrumenten', 16),
    ('Blokfluiten', 21),
    ('Trombones', 21),
    ('Trompetten', 21),
    ('Tuba''s', 21),
    ('Keyboards en piano''s', 16),
    ('Keyboards', 26),
    ('Piano''s', 26),
    ('Transport', NULL),
    ('Auto''s', 29),
    ('Aanhangers', 29),
    ('Boten', 29),
    ('Tweewielers', 29),
    ('Brommers en scooters', 33),
    ('Brommers', 34),
    ('Fietsen', 33),
    ('Motoren', 33),
    ('Scooters', 34),
    ('Overig', 29)